name: _Base Deploy 
on:
  workflow_call:
    inputs:
      Environment:
        required: true
        type: string
      Title:
        required: true
        type: string
    secrets:
      az_credentials:
        required: true

env:
  AZURE_WEBAPP_NAME: "cicdpoc-prod"    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './aspnet-core-dotnet-core'             # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.x'                  # set this to the dot net version to use
  RESOURCEGROUPNAME: "rg-cicd-poc-mp"
  LOCATION: "Australia Southeast"
  HOSTINGPLANNAME: "asp-cicd-poc-mp"
  APPINSIGHTLOCATION: "Australia Southeast"
  SKU: "S1 Standard"

jobs:
  Deploy:
    name: Deploy To ${{inputs.Environment}}
    runs-on: ubuntu-latest
    environment:
        name: ${{inputs.Environment}}
        url: http://cicdpoc-prod.azurewebsites.net/ 
    env:
      Title: ${{inputs.Environment}} Environment
    
    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v2
      continue-on-error: false
      with:
        name: buildartifacts
        path: buildartifacts

    - name: Unzipping Build artifact
      run: |
        unzip -qq ./buildartifacts/Application.zip -d .
    
    - name: Login to Azure
      uses: azure/login@v1
      continue-on-error: false
      with:
        creds: ${{ secrets.az_credentials }}
    
    - name: Echo login details
      run: |
        echo "${{secrets.az_credentials.clientId}}"
        echo "Environment is ${{inputs.Environment}}"
        echo ${{secrets.az_credentials.clientId}}
        echo ${{secrets.az_credentials.subscriptionId}}
        echo ${{secrets.az_credentials.clientSecret}}
        echo ${{secrets.az_credentials.tenantId}}
    
      
    - name: Azure key vault - Get Secrets
      uses: Azure/get-keyvault-secrets@v1
      id: GetAzureSecrets
      with:
        # Name of the azure key vault
        keyvault: kv-cicd-poc-${{inputs.Environment}}
        # Name of the secret to be fetched
        secrets: topsecret
    - name: Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        # comma separated list of XML/JSON/YAML files in which tokens are to be substituted. Files names must be specified relative to the folder-path.
        files: '**/appsettings.json'
      env:
        SampleConfig.Title: ${{inputs.Title}}
        SampleConfig.SuperSecret: ${{steps.GetAzureSecrets.outputs.topsecret}}
  
    - name: 'Deploy web app'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: './Application/build'
