name: _Base Build 
on:
  workflow_call:

env:
  DOTNET_VERSION: '6.0.201'                  # set this to the dot net version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checkout the repo
    - uses: actions/checkout@master
    
    - name: Creating artifact directories
      run: |
        mkdir buildartifacts
        mkdir deploymenttemplates

    # Setup .NET Core SDK
    - name: Setup .NET Core
      uses: xt0rted/setup-dotnet@v1.0.0 #actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }} 
    
    # Run dotnet build and publish
    - name: dotnet build unit test and publish
      run: |
        cd Application
        dotnet restore
        dotnet build --configuration Release
        # dotnet test aspnet-core-dotnet-core.UnitTests/aspnet-core-dotnet-core.UnitTests.csproj
        dotnet publish -c Release -o './build'
    - name: archive application
      run: | 
        zip -qq -r ./buildartifacts/Application.zip ./Application/build

    - name: Upload Application to Build Artifact
      continue-on-error: false
      uses: actions/upload-artifact@v2
      with:
        name: buildartifacts
        path: buildartifacts
