name: 'Terraform'

on:
  workflow_dispatch:

env:
  name: SystemTest

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: $env.name
    steps:
 #   - name: Azure Login
#      uses: Azure/login@v1.4.3
#      with:
#        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
#        creds: ${{secrets.AZURE_CREDENTIALS}}
#        subscription-id: ${{secrets.AZ_SUBSCRIPTIONID}}
 #       enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install Terraform
      working-directory: Application/Terraform/
      run: |
          echo "Enviornment is ${{env.name}}"
          pwd
          ls
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install terraform
          export ARM_CLIENT_ID=${{secrets.AZ_CLIENTID}}
          export ARM_CLIENT_SECRET=${{secrets.AZ_CLIENTSECRET}}
          export ARM_SUBSCRIPTION_ID=${{secrets.AZ_SUBSCRIPTIONID}}
          export ARM_TENANT_ID=${{secrets.AZ_TENANTID}}
          terraform workspace add ${{env.name}}
          terraform workspace select ${{env.name}}
          terraform init
          terraform plan -auto-approve -var-file=${{env.name}}.tfvars
          terraform apply -auto-approve -var-file=${{env.name}}.tfvars
          
