name: 'Base Terraform Deploy'

on:
  workflow_call:
    inputs:
      Environment:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
      AZURE_TENANTID:
        required: true
      AZURE_CLIENTID:
        required: true
      AZURE_CLIENTSECRET:
        required: true
      AZURE_SUBSCRIPTIONID:
        required: true
    outputs:
      AppURL:
        description: "Application URL"
        value: ${{ jobs.terraform.outputs.output1 }}
      AppName:
        description: "Application Name"
        value: ${{ jobs.terraform.outputs.output2 }}

        
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    outputs:
      AppName: ${{ steps.terraformStep.outputs.AppName }}
      AppURL: ${{ steps.terraformStep.outputs.AppURL }}

    environment: 
      name: ${{inputs.Environment}}
      url: ${{ steps.terraformStep.outputs.AppURL }}
    steps:
    - name: Azure Login
      uses: Azure/login@v1.4.3
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{secrets.AZURE_CREDENTIALS}}
       # subscription-id: ${{secrets.AZURE_SUBSCRIPTIONID}}
      #  enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install Terraform
      id: terraformStep
      working-directory: Application/Terraform/
      run: |
          echo "Enviornment is ${{inputs.Environment}}"
          pwd
          ls
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install terraform
          export ARM_CLIENT_ID=${{secrets.AZURE_CLIENTID}}
          export ARM_CLIENT_SECRET=${{secrets.AZURE_CLIENTSECRET}}
          export ARM_SUBSCRIPTION_ID=${{secrets.AZURE_SUBSCRIPTIONID}}
          export ARM_TENANT_ID=${{secrets.AZURE_TENANTID}}
          terraform init
          terraform workspace add ${{inputs.Environment}}
          terraform workspace select ${{inputs.Environment}}
          terraform plan -var-file=${{inputs.Environment}}.tfvars
          terraform apply -auto-approve -var-file=${{inputs.Environment}}.tfvars
          AppURL = `terraform output ApplicationURL`
          AppName = `terraform output ApplicationName`
          echo "::set-output name=AppURL::$AppURL"
          echo "::set-output name=AppName::$AppName"
          echo "::set-output name=AppURL::${}"
