# This is a basic workflow to help you get started with Actions

name: Automatic CI & CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]
    types:
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  BuildApplication:
    uses: meetmitul/az303/.github/workflows/_base-build.yml@master

  DeployInfraToDev:
    uses: meetmitul/az303/.github/workflows/_terraform.yml@master
    #if: ${{ true==false }}
    with:
      Environment: Development
    secrets:
#      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_TENANTID: ${{ secrets.AZ_TENANTID }}
      AZURE_CLIENTID: ${{ secrets.AZ_CLIENTID }}
      AZURE_CLIENTSECRET: ${{ secrets.AZ_CLIENTSECRET }}
      AZURE_SUBSCRIPTIONID: ${{ secrets.AZ_SUBSCRIPTIONID }}
              
  ReassignOutputVariablesForDevelopment:
    runs-on: ubuntu-latest
    needs: DeployInfraToDev
    outputs:
      APPNAME: ${{steps.replaceVariable.outputs.APPNAME}}
      APPURL: ${{steps.replaceVariable.outputs.APPURL}}
    steps:
      - name: Replace name of AppName
        id: replaceVariable
        run: |
          echo  ${{needs.DeployInfraToDev.outputs.AppName}}
          AppName=${{needs.DeployInfraToDev.outputs.AppName}}
          echo $AppName
          echo "::set-output name=APPNAME::$AppName"
          echo ${{needs.ReassignOutputVariablesForDevelopment.outputs.APPNAME}}
          
          echo  ${{needs.DeployInfraToDev.outputs.AppURL}}
          AppURL=${{needs.DeployInfraToDev.outputs.AppURL}}
          echo $AppURL
          echo "::set-output name=APPURL::$AppURL"
          echo ${{needs.ReassignOutputVariablesForDevelopment.outputs.APPURL}}
          
          
         
  DeployAppToDev:
    uses: meetmitul/az303/.github/workflows/_base-deployment.yml@master
    #if: false
    needs: 
      - BuildApplication
      - DeployInfraToDev
      - ReassignOutputVariablesForDevelopment
    with:
      Title: Development Title
      Environment: Development
      AppName: ${{needs.ReassignOutputVariablesForDevelopment.outputs.APPNAME}}
      AppURL: ${{needs.ReassignOutputVariablesForDevelopment.outputs.APPURL}}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  
  DeployInfraToSysTest:
    uses: meetmitul/az303/.github/workflows/_terraform.yml@master
    #if: ${{ true==false }}
    with:
      Environment: SystemTest
    secrets:
#      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_TENANTID: ${{ secrets.AZ_TENANTID }}
      AZURE_CLIENTID: ${{ secrets.AZ_CLIENTID }}
      AZURE_CLIENTSECRET: ${{ secrets.AZ_CLIENTSECRET }}
      AZURE_SUBSCRIPTIONID: ${{ secrets.AZ_SUBSCRIPTIONID }}
              
  ReassignOutputVariablesForSysTest:
    runs-on: ubuntu-latest
    needs: DeployInfraToSysTest
    outputs:
      APPNAME: ${{steps.replaceVariable.outputs.APPNAME}}
      APPURL: ${{steps.replaceVariable.outputs.APPURL}}
    steps:
      - name: Replace name of AppName
        id: replaceVariable
        run: |
          echo  ${{needs.DeployInfraToSysTest.outputs.AppName}}
          AppName=${{needs.DeployInfraToSysTest.outputs.AppName}}
          echo $AppName
          echo "::set-output name=APPNAME::$AppName"
          echo ${{needs.ReassignOutputVariablesForSysTest.outputs.APPNAME}}
          
          echo  ${{needs.DeployInfraToSysTest.outputs.AppURL}}
          AppURL=${{needs.DeployInfraToSysTest.outputs.AppURL}}
          echo $AppURL
          echo "::set-output name=APPURL::$AppURL"
          echo ${{needs.ReassignOutputVariablesForSysTest.outputs.APPURL}}
          
          
  DeployAppToSysTest:
    uses: meetmitul/az303/.github/workflows/_base-deployment.yml@master
    #if: false
    needs: 
      - BuildApplication
      - DeployInfraToSysTest
      - ReassignOutputVariablesForSysTest
      - DeployAppToDev
    with:
      Title: System Test Title
      Environment: SystemTest
      AppName: ${{needs.ReassignOutputVariablesForSysTest.outputs.APPNAME}}
      AppURL: ${{needs.ReassignOutputVariablesForSysTest.outputs.APPURL}}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    
    
  DeployInfraToProduction:
    uses: meetmitul/az303/.github/workflows/_terraform.yml@master
    #if: ${{ true==false }}
    needs: DeployAppToSysTest
    with:
      Environment: Production
    secrets:
#      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_TENANTID: ${{ secrets.AZ_TENANTID }}
      AZURE_CLIENTID: ${{ secrets.AZ_CLIENTID }}
      AZURE_CLIENTSECRET: ${{ secrets.AZ_CLIENTSECRET }}
      AZURE_SUBSCRIPTIONID: ${{ secrets.AZ_SUBSCRIPTIONID }}
              
  ReassignOutputVariablesForProduction:
    runs-on: ubuntu-latest
    needs: DeployInfraToProduction
    outputs:
      APPNAME: ${{steps.replaceVariable.outputs.APPNAME}}
      APPURL: ${{steps.replaceVariable.outputs.APPURL}}
    steps:
      - name: Replace name of AppName
        id: replaceVariable
        run: |
          echo  ${{needs.DeployInfraToProduction.outputs.AppName}}
          AppName=${{needs.DeployInfraToProduction.outputs.AppName}}
          echo $AppName
          echo "::set-output name=APPNAME::$AppName"
          echo ${{needs.ReassignOutputVariablesForProduction.outputs.APPNAME}}
          
          echo  ${{needs.DeployInfraToProduction.outputs.AppURL}}
          AppURL=${{needs.DeployInfraToProduction.outputs.AppURL}}
          echo $AppURL
          echo "::set-output name=APPURL::$AppURL"
          echo ${{needs.ReassignOutputVariablesForProduction.outputs.APPURL}}
          
          
  DeployAppToProduction:
    uses: meetmitul/az303/.github/workflows/_base-deployment.yml@master
    #if: false
    needs: 
      - BuildApplication
      - DeployInfraToProduction
      - ReassignOutputVariablesForProduction
      - DeployAppToSysTest
      - DeployAppToDev
    with:
      Title: Production Title
      Environment: Production
      AppName: ${{needs.ReassignOutputVariablesForProduction.outputs.APPNAME}}
      AppURL: ${{needs.ReassignOutputVariablesForProduction.outputs.APPURL}}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    
