# This is a basic workflow to help you get started with Actions

name: CI & CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types:
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  DeployInfraToDev:
    uses: meetmitul/az303/.github/workflows/_terraform.yml@master
    #if: ${{ true==false }}
    with:
      Environment: Development
    secrets:
#      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_TENANTID: ${{ secrets.AZ_TENANTID }}
      AZURE_CLIENTID: ${{ secrets.AZ_CLIENTID }}
      AZURE_CLIENTSECRET: ${{ secrets.AZ_CLIENTSECRET }}
      AZURE_SUBSCRIPTIONID: ${{ secrets.AZ_SUBSCRIPTIONID }}
      
  BuildApplication:
    uses: meetmitul/az303/.github/workflows/_base-build.yml@master
        
  RecreateWebAppNameForDev:
    runs-on: ubuntu-latest
    needs: DeployInfraToDev
    outputs:
      APPNAME: ${{steps.replaceVariable.outputs.APPNAME}}
    steps:
      - name: Replace name of AppName
        id: replaceVariable
        run: |
          echo  ${{needs.DeployInfraToDev.outputs.AppName}}
          AppName=${{needs.DeployInfraToDev.outputs.AppName}}
          echo $AppName
          echo "::set-output name=APPNAME::$AppName"
          echo ${{needs.RecreateWebAppNameForDev.outputs.APPNAME}}
          
          
  DeployAppToDev:
    uses: meetmitul/az303/.github/workflows/_base-deployment.yml@master
    #if: false
    needs: 
      - BuildApplication
      - DeployInfraToDev
      - RecreateWebAppNameForDev
    with:
      Title: Development Title
      Environment: Development
      AppName: ${{needs.RecreateWebAppNameForDev.outputs.APPNAME}}
      AppURL: ${{needs.DeployInfraToDev.outputs.AppName}}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  DeployInfraToSysTest:
    uses: meetmitul/az303/.github/workflows/_terraform.yml@master
    #if: ${{ true==false }}
    with:
      Environment: SystemTest
    secrets:
#      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_TENANTID: ${{ secrets.AZ_TENANTID }}
      AZURE_CLIENTID: ${{ secrets.AZ_CLIENTID }}
      AZURE_CLIENTSECRET: ${{ secrets.AZ_CLIENTSECRET }}
      AZURE_SUBSCRIPTIONID: ${{ secrets.AZ_SUBSCRIPTIONID }}
              
  RecreateWebAppNameForSysTest:
    runs-on: ubuntu-latest
    needs: DeployInfraToSysTest
    outputs:
      APPNAME: ${{steps.replaceVariable.outputs.APPNAME}}
    steps:
      - name: Replace name of AppName
        id: replaceVariable
        run: |
          echo  ${{needs.DeployInfraToSysTest.outputs.AppName}}
          AppName=${{needs.DeployInfraToSysTest.outputs.AppName}}
          echo $AppName
          echo "::set-output name=APPNAME::$AppName"
          echo ${{needs.RecreateWebAppNameForSysTest.outputs.APPNAME}}
          
          
  DeployAppToSysTest:
    uses: meetmitul/az303/.github/workflows/_base-deployment.yml@master
    #if: false
    needs: 
      - BuildApplication
      - DeployInfraToSysTest
      - RecreateWebAppNameForSysTest
    with:
      Title: System Test Title
      Environment: SystemTest
      AppName: ${{needs.RecreateWebAppNameForSysTest.outputs.APPNAME}}
      AppURL: ${{needs.DeployInfraToSysTest.outputs.AppName}}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    
    
  DeployInfraToProduction:
    uses: meetmitul/az303/.github/workflows/_terraform.yml@master
    #if: ${{ true==false }}
    with:
      Environment: Production
    secrets:
#      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_TENANTID: ${{ secrets.AZ_TENANTID }}
      AZURE_CLIENTID: ${{ secrets.AZ_CLIENTID }}
      AZURE_CLIENTSECRET: ${{ secrets.AZ_CLIENTSECRET }}
      AZURE_SUBSCRIPTIONID: ${{ secrets.AZ_SUBSCRIPTIONID }}
              
  RecreateWebAppNameForProduction:
    runs-on: ubuntu-latest
    needs: DeployInfraToProduction
    outputs:
      APPNAME: ${{steps.replaceVariable.outputs.APPNAME}}
    steps:
      - name: Replace name of AppName
        id: replaceVariable
        run: |
          echo  ${{needs.DeployInfraToProduction.outputs.AppName}}
          AppName=${{needs.DeployInfraToProduction.outputs.AppName}}
          echo $AppName
          echo "::set-output name=APPNAME::$AppName"
          echo ${{needs.RecreateWebAppNameForProduction.outputs.APPNAME}}
          
          
  DeployAppToProduction:
    uses: meetmitul/az303/.github/workflows/_base-deployment.yml@master
    #if: false
    needs: 
      - BuildApplication
      - DeployInfraToProduction
      - RecreateWebAppNameForProduction
    with:
      Title: Production Title
      Environment: Production
      AppName: ${{needs.RecreateWebAppNameForProduction.outputs.APPNAME}}
      AppURL: ${{needs.DeployInfraToProduction.outputs.AppName}}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    
