# This is a basic workflow to help you get started with Actions

name: Create Tag

# Controls when the workflow will run
on:
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ApplyNewTag:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repo
    - uses: actions/checkout@v2
      with:
        fetch-depth: 20

    - name: Echo New Tag
      run: |
        git fetch --tags
        latestVersion=$(git describe --tags --always --abbrev=0)
        majorVersion=$(latestVersion | cut -d '.' -f 1 | cut -d 'v' -f 2)
        minorVersion=$(latestVersion | cut -d '.' -f 2)
        hotFixrVersion=$(latestVersion | cut -d '.' -f 3)
        echo $latestVersion
        echo $majorVersion
        echo $minorVersion
        newVersion="v$majorVersion.$((mionrVersion + 1)).$hotFixVersion"
        echo $newVersion
        echo "Assign New Tag"
        echo $newVersion
        git tag $newVersion
        git push --tags
