# This is a basic workflow to help you get started with Actions

name: Create Tag

# Controls when the workflow will run
on:
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CreateNewTag:
    runs-on: ubuntu-latest
    outputs:
      newTagName: ${{ steps.idNewTag.outputs.TAG_NAME }}
    steps:
    - id: idNewTag
    # Checkout the repo
    - uses: actions/checkout@v2
      with:
        fetch-depth: 20
    - name: Echo New Tag
      run: |
        git fetch --tags
        latestVersion=$(git describe --tags --always --abbrev=0 --match v*.*.*)
        majorVersion=`echo $latestVersion | cut -d '.' -f 1 | cut -d 'v' -f 2`
        minorVersion=`echo $latestVersion | cut -d '.' -f 2`
        hotFixVersion=`echo $latestVersion | cut -d '.' -f 3`
        echo Latest Version : $latestVersion
        echo Major Version : $majorVersion
        echo Minor Version : $minorVersion
        echo Hotfix Version : $hotFixVersion
        newVersion="v$majorVersion.$((minorVersion + 1)).0"
        echo New Version : $newVersion
        git tag $newVersion
        git push --tags
        echo New tag pushed to repository
        echo "::set-output name=TAG_NAME::$newVersion"
      
  CreateNewRelease:
    needs: CreateNewTag
    uses: meetmitul/az303/.github/workflows/createrelease.yml@master
    with:
      TagName: ${{ needs.CreateNewTag.steps.idNewTag.outputs.newTagName}}
