name: Deploy to test 
on:
  workflow_dispatch:
  
jobs:
#  build:
#    uses: meetmitul/az303/.github/workflows/_base-build.yml@master
    
  DeployInfraToTest:
    uses: meetmitul/az303/.github/workflows/_terraform.yml@master
    #needs: build
    with:
      Environment: SystemTest

    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_TENANTID: ${{ secrets.AZ_TENANTID }}
      AZURE_CLIENTID: ${{ secrets.AZ_CLIENTID }}
      AZURE_CLIENTSECRET: ${{ secrets.AZ_CLIENTSECRET }}
      AZURE_SUBSCRIPTIONID: ${{ secrets.AZ_SUBSCRIPTIONID }}
  
  BuildApplication:
    uses: meetmitul/az303/.github/workflows/_base-build.yml@master
    
  DeployApplicationToTest:
    uses: meetmitul/az303/.github/workflows/_base-deployment.yml@master
    needs: 
      - BuildApplication
      - DeployInfraToTest
    with:
      Title: System Test
      Environment: SystemTest
      AppName: ${{ needs.DeployInfraToTest.outputs.AppName }}
      AppURL: ${{ needs.DeployInfraToTest.outputs.AppURL }}
    secrets:
      az_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    
