name: Deploy to test 
on:
  workflow_dispatch:
  
jobs:
  deployToTest:
    uses: meetmitul/az303/.github/workflows/deploy-to-test.yml@main
    with:
      Title: TEST1
    secrets:
      az_credentials: ${{ secrets.AZURE_CREDENTIALS }}
