name: Deploy to test 
on:
  workflow_dispatch:
  
jobs:
  deployToTest:
    uses: meetmitul/az303/.github/workflows/base-testdeployment.yml.yml@master
    with:
      Title: TEST1
    secrets:
      az_credentials: ${{ secrets.AZURE_CREDENTIALS }}
