name: Deploy to test 
on:
  workflow_dispatch:
  
jobs:
  build:
    uses: meetmitul/az303/.github/workflows/_base-build.yml@master
    
  deployToTest:
    uses: meetmitul/az303/.github/workflows/_base-deployment.yml@master
    with:
      Title: TEST1
      Environment: Test
    secrets:
      az_credentials: ${{ secrets.AZURE_CREDENTIALS }}
