name: Deploy to test 
on:
  workflow_dispatch:
  
jobs:
#  build:
#    uses: meetmitul/az303/.github/workflows/_base-build.yml@master
    
  deployToTest:
    uses: meetmitul/az303/.github/workflows/_terraform.yml@master
    #needs: build
    with:
      Environment: SystemTest
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_TENANTID: ${{ secrets.AZURE_TENANTID }}
      AZURE_CLIENTID: ${{ secrets.AZURE_CLIENTID }}
      AZURE_CLIENTSECRET: ${{ secrets.AZURE_CLIENTSECRET }}
      AZURE_SUBSCRIPTIONID: ${{ secrets.AZURE_SUBSCRIPTIONID }}
      
