name: Deploy to test 
on:
  workflow_dispatch:
env:
  aName: helloworld
jobs:          
  DeployInfraToTest:
    uses: meetmitul/az303/.github/workflows/_terraform.yml@master
    #if: ${{ true==false }}
    with:
      Environment: SystemTest

    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_TENANTID: ${{ secrets.AZ_TENANTID }}
      AZURE_CLIENTID: ${{ secrets.AZ_CLIENTID }}
      AZURE_CLIENTSECRET: ${{ secrets.AZ_CLIENTSECRET }}
      AZURE_SUBSCRIPTIONID: ${{ secrets.AZ_SUBSCRIPTIONID }}
      
  BuildApplication:
    uses: meetmitul/az303/.github/workflows/_base-build.yml@master
        
  RecreateWebAppName:
    runs-on: ubuntu-latest
    needs: DeployInfraToTest
    outputs:
      APPNAME: ${{steps.replaceVariable.outputs.APPNAME}}
    steps:
      - name: Replace name of AppName
        id: replaceVariable
        run: |
          echo  ${{needs.DeployInfraToTest.outputs.AppName}}
          AppName=${{needs.DeployInfraToTest.outputs.AppName}}
          echo $AppName
          echo "::set-output name=APPNAME::$AppName"
          echo ${{needs.RecreateWebAppName.outputs.APPNAME}}
          echo "Environment variable - ${{eng.aName}}
          
  DeployApplicationToTest:
    uses: meetmitul/az303/.github/workflows/_base-deployment.yml@master
    #if: false
    needs: 
      - BuildApplication
      - DeployInfraToTest
      - RecreateWebAppName
    with:
      Title: System Test
      Environment: SystemTest
      #AppName: ${{needs.DeployInfraToTest.outputs.AppName}}
      AppName: ${{needs.RecreateWebAppName.outputs.APPNAME}}
      AppURL: ${{needs.DeployInfraToTest.outputs.AppName}}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    
