name: Deploy to test 
on:
  workflow_dispatch:
  
jobs:
#  build:
#    uses: meetmitul/az303/.github/workflows/_base-build.yml@master
    
  deployToTest:
    uses: meetmitul/az303/.github/workflows/_terraform.yml@master
    #needs: build
    with:
      Environment: SystemTest
      URL: ${{ needs.deployToTest.outputs.AppURL }}

    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_TENANTID: ${{ secrets.AZ_TENANTID }}
      AZURE_CLIENTID: ${{ secrets.AZ_CLIENTID }}
      AZURE_CLIENTSECRET: ${{ secrets.AZ_CLIENTSECRET }}
      AZURE_SUBSCRIPTIONID: ${{ secrets.AZ_SUBSCRIPTIONID }}
   
  OutputURLs:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.deployToTest.outputs.AppName }} - ${{ needs.deployToTest.outputs.AppURL }}

      
