name: Deploy to test 
on:
  workflow_dispatch:
  
jobs:
#  build:
#    uses: meetmitul/az303/.github/workflows/_base-build.yml@master
    
  deployToTest:
    uses: meetmitul/az303/.github/workflows/_terraform.yml@master
    #needs: build
    with:
      Environment: SystemTest
    secrets:
      az_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      
