name: Deploy to Development 
on:
  workflow_dispatch:
  
jobs:
    
  DeployInfra:
    uses: meetmitul/az303/.github/workflows/_terraform.yml@master
    with:
      Environment: Development

    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_TENANTID: ${{ secrets.AZ_TENANTID }}
      AZURE_CLIENTID: ${{ secrets.AZ_CLIENTID }}
      AZURE_CLIENTSECRET: ${{ secrets.AZ_CLIENTSECRET }}
      AZURE_SUBSCRIPTIONID: ${{ secrets.AZ_SUBSCRIPTIONID }}
  
  BuildApplication:
    uses: meetmitul/az303/.github/workflows/_base-build.yml@master
    
  DeployApplication:
    uses: meetmitul/az303/.github/workflows/_base-deployment.yml@master
    needs: 
      - BuildApplication
      - DeployInfra
    with:
      Title: DevelopmentTitle
      Environment: Development 
      AppName: ${{ needs.DeployInfraToTest.outputs.AppName }}
      AppURL:  ${{ needs.DeployInfraToTest.outputs.AppURL }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    
