name: Deploy to test 
on:
  workflow_dispatch:

jobs:          
  DeployInfraToTest:
    uses: meetmitul/az303/.github/workflows/_terraform.yml@master
    if: ${{ true==false }}
    #needs: build
    with:
      Environment: SystemTest

    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_TENANTID: ${{ secrets.AZ_TENANTID }}
      AZURE_CLIENTID: ${{ secrets.AZ_CLIENTID }}
      AZURE_CLIENTSECRET: ${{ secrets.AZ_CLIENTSECRET }}
      AZURE_SUBSCRIPTIONID: ${{ secrets.AZ_SUBSCRIPTIONID }}
      
  BuildApplication:
    uses: meetmitul/az303/.github/workflows/_base-build.yml@master
        
  RecreateWebAppNae:
    runs-on: ubuntu-latest
    needs: DeployInfraToTest
    env:
      AppName: xxxx
    steps:
      - name: Replace name of AppName
        run: |
          echo  ${{needs.DeployInfraToTest.outputs.AppName}}
          $AppName=${{needs.DeployInfraToTest.outputs.AppName}}
          echo $AppName
          
  DeployApplicationToTest:
    uses: meetmitul/az303/.github/workflows/_base-deployment.yml@master
    #if: false
    needs: 
      - BuildApplication
      - DeployInfraToTest
    with:
      Title: System Test
      Environment: SystemTest
      #AppName: ${{needs.DeployInfraToTest.outputs.AppName}}
      AppName: ${{RecreateWebAppNae.AppName}}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    
