name: Deploy to Production 
on:
  workflow_dispatch:
jobs:          
  DeployInfra:
    uses: meetmitul/az303/.github/workflows/_terraform.yml@master
    #if: ${{ true==false }}
    with:
      Environment: ${{ env.ENVIRONMENT_NAME }}
    secrets:
      #AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_TENANTID: ${{ secrets.AZ_TENANTID }}
      AZURE_CLIENTID: ${{ secrets.AZ_CLIENTID }}
      AZURE_CLIENTSECRET: ${{ secrets.AZ_CLIENTSECRET }}
      AZURE_SUBSCRIPTIONID: ${{ secrets.AZ_SUBSCRIPTIONID }}
      
  BuildApplication:
    uses: meetmitul/az303/.github/workflows/_base-build.yml@master
        
  ReassignOutputVariables:
    runs-on: ubuntu-latest
    needs: DeployInfra
    outputs:
      APPNAME: ${{steps.replaceVariable.outputs.APPNAME}}
      APPURL: ${{steps.replaceVariable.outputs.APPURL}}
    steps:
      - name: Replace name of AppName
        id: replaceVariable
        run: |
          echo  ${{needs.DeployInfra.outputs.AppName}}
          AppName=${{needs.DeployInfra.outputs.AppName}}
          echo $AppName
          echo "::set-output name=APPNAME::$AppName"
          echo ${{needs.RecreateWebAppName.outputs.APPNAME}}
          
          echo  ${{needs.DeployInfra.outputs.AppURL}}
          AppURL=${{needs.DeployInfra.outputs.AppURL}}
          echo $AppURL
          echo "::set-output name=APPURL::$AppURL"
          echo ${{needs.ReassignOutputVariables.outputs.APPURL}}
          
  DeployApplication:
    uses: meetmitul/az303/.github/workflows/_base-deployment.yml@master
    #if: false
    needs: 
      - BuildApplication
      - DeployInfra
      - ReassignOutputVariables
    with:
      Title: $Environment - Title
      Environment: Production
      AppName: ${{needs.ReassignOutputVariables.outputs.APPNAME}}
      AppURL: ${{needs.ReassignOutputVariables.outputs.APPURL}}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    
