name: Deploy to Development 
on:
  workflow_dispatch:
  
jobs:
  build:
    uses: meetmitul/az303/.github/workflows/_base-build.yml@master
    
  DevInfrastructure:
    uses: meetmitul/az303/.github/workflows/_terraform.yml@master
    #needs: build
    with:
      Environment: Development
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_TENANTID: ${{ secrets.AZ_TENANTID }}
      AZURE_CLIENTID: ${{ secrets.AZ_CLIENTID }}
      AZURE_CLIENTSECRET: ${{ secrets.AZ_CLIENTSECRET }}
      AZURE_SUBSCRIPTIONID: ${{ secrets.AZ_SUBSCRIPTIONID }}
      
 # deployToDev:
 #   uses: meetmitul/az303/.github/workflows/_base-deployment.yml@master
 #   needs: build
 #   with:
 #     Title: Development1
 #     Environment: Development
 #   secrets:
 #     az_credentials: ${{ secrets.AZURE_CREDENTIALS }}    
