name: Deploy to test 
on:
  workflow_dispatch:
env:
  AppName: app-cicd-demo-SystemTest #${{jobs.DeployInfraToTest.outputs.AppName}}  

jobs:          
  DeployInfraToTest:
    uses: meetmitul/az303/.github/workflows/_terraform.yml@master
    if: ${{ true==false }}
    #needs: build
    with:
      Environment: SystemTest

    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_TENANTID: ${{ secrets.AZ_TENANTID }}
      AZURE_CLIENTID: ${{ secrets.AZ_CLIENTID }}
      AZURE_CLIENTSECRET: ${{ secrets.AZ_CLIENTSECRET }}
      AZURE_SUBSCRIPTIONID: ${{ secrets.AZ_SUBSCRIPTIONID }}
      
  BuildApplication:
    uses: meetmitul/az303/.github/workflows/_base-build.yml@master

  EchoEnv:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo environment variable is $AppName
        


  DeployApplicationToTest:
    uses: meetmitul/az303/.github/workflows/_base-deployment.yml@master
    #if: false
    needs: 
      - BuildApplication
      #- DeployInfraToTest
    with:
      Title: System Test
      Environment: SystemTest
      AppName: ${{needs.DeployInfraToTest.outputs.AppName}}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    
