name: SwapSlots

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:
  schedule:
    - cron: "25,50 * * * *"   # <=== Change this value . this is 6AM utc which is 5pm AEST
    #- cron: "0 6 * * *"   # <=== Change this value . this is 6AM utc which is 5pm AEST
jobs:
  swapslot:
    runs-on: ubuntu-latest
    environment: Development
    steps:
    - name: Login to Azure
      uses: Azure/login@v2.2.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      continue-on-error: false

    - uses: Azure/cli@v2.1.0
      with:
      # Specify the script here
        inlineScript: 
          az webapp deployment slot swap  -g rg-cicd-demo-development -n app-cicd-demo-Development --slot staging-slot --target-slot production

      # Azure CLI version to be used to execute the script. If not provided, latest version is used
        # azcliversion: # optional, default is agentazcliversion
          
